[package]
name = "dns-guide"
version = "0.1.0"
authors = ["yanghao <928131755@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

